navis_one/navis/urls.py
from django.urls import path
from . import views
app_name = 'navis'

urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('<slug:category_slug>/', views.product_list, name='product_list'),
    path('<slug:category_slug>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('search/', views.Search.as_view(), name='search'),
]

navis_one/navis_one/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static

urlpatterns = [
    path('admin-view/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('', include('navis.urls', namespace='navis')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

navis_one/navis/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=300)
    info = models.TextField("Info", null=True, blank=True)
    comment = models.CharField(max_length=300, null=True, blank=True)
    url = models.SlugField(max_length=300, unique=True)
    image = models.ImageField(upload_to="catalog_image/", null=True, blank=True)
    source_category = models.CharField(max_length=300, null=True, blank=True)

    def __str__(self):
        return str(self.url)

    def get_absolute_url(self):
        return reverse('navis:product_list', args=[self.url])

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"


class Filter(models.Model):
    name = models.CharField(max_length=300)
    comment = models.CharField(max_length=300, null=True, blank=True)
    url = models.SlugField(max_length=300, unique=True)

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name = "Filter"
        verbose_name_plural = "Filters"


class Commercial(models.Model):
    name = models.CharField(max_length=300)
    category = models.ForeignKey(Category,
                                 on_delete=models.SET_NULL, related_name="commercial_category", null=True, blank=True)
    comment = models.CharField(max_length=300, null=True, blank=True)
    url = models.SlugField(max_length=300, unique=True)
    image = models.ImageField(upload_to="commercial_image/", null=True, blank=True)
    source_commercial = models.CharField(max_length=300, null=True, blank=True)
    source_category = models.CharField(max_length=300, null=True, blank=True)

    def __str__(self):
        return str(self.url)

    class Meta:
        verbose_name = "Commercial"
        verbose_name_plural = "Commercials"


class Product(models.Model):
    source_id = models.CharField(max_length=300, null=True, blank=True)
    article = models.CharField(max_length=300, null=True, blank=True)
    name = models.CharField(max_length=300, null=True, blank=True)
    category = models.ForeignKey(Category,
                                 on_delete=models.SET_NULL, related_name="product_category", null=True, blank=True)
    specification = models.CharField(max_length=300, null=True, blank=True)
    advanced_description = models.TextField("Advanced description", null=True, blank=True)
    is_active = models.BooleanField(default=1, null=True)
    comment = models.CharField(max_length=300, null=True, blank=True)
    filter = models.ManyToManyField(Filter, related_name="product_filter", blank=True)
    slug = models.SlugField(max_length=300, unique=True)
    commercial = models.ForeignKey(Commercial,
                                   on_delete=models.SET_NULL, related_name="product_commercial", null=True, blank=True)
    source_commercial = models.CharField(max_length=300, null=True, blank=True)
    source_category = models.CharField(max_length=300, null=True, blank=True)

    def __str__(self):
        return str(self.article)

    def get_absolute_url(self):
        return reverse('navis:product_detail', args=[self.category.url, self.slug])

    class Meta:
        verbose_name = "Product"
        verbose_name_plural = "Products"


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True)
    source_product = models.CharField(max_length=300, null=True, blank=True)
    image_url = models.URLField(max_length=300, null=True, blank=True)

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = "ProductImage"
        verbose_name_plural = "ProductImages"


class ContentCategory(models.Model):
    name = models.CharField(max_length=300)
    comment = models.CharField(max_length=300, null=True, blank=True)
    url = models.SlugField(max_length=300, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "ContentCategory"
        verbose_name_plural = "ContentCategories"


class Content(models.Model):
    alias = models.SlugField(max_length=300, unique=True)
    published = models.BooleanField(default=0)
    main_image = models.ImageField(upload_to="content/main_image/", blank=True, null=True)
    category = models.ForeignKey(
        ContentCategory, on_delete=models.SET_NULL, related_name="content_category", null=True, blank=True)
    title = models.CharField(max_length=300, null=True)
    full_text = models.TextField(null=True)

    def __str__(self):
        return self.alias

    class Meta:
        verbose_name = "Content"
        verbose_name_plural = "Contents"

navis_one/navis/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, View
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import *


def index(request):
    return render(request, 'navis_one/index.html')


def about(request):
    return render(request, 'navis_one/about.html')


def contact(request):
    return render(request, 'navis_one/contact.html')


def product_list(request, category_slug):
    categories = Category.objects.all()
    products = Product.objects.all()
    category = get_object_or_404(Category, url=category_slug)
    products = products.filter(category=category)
    context = {'category': category, 'categories': categories, 'products': products}
    return render(request, 'navis_one/product/product_list.html', context)


def product_detail(request, category_slug, slug):
    product = get_object_or_404(Product, slug=slug)
    category = get_object_or_404(Category, url=category_slug)
    context = {'category': category, 'product': product}
    return render(request, 'navis_one/product/product_detail.html', context)


class Search(ListView):
    paginate_by = 15

    def get_queryset(self):
        return Product.objects.filter(title__icontains=self.request.GET.get("q"))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["q"] = f'q={self.request.GET.get("q")}&'
        return context

navis_one/templates/navis_one/about.html
{% extends 'navis_one/main.html' %}
{% load static i18n navis_tag %}
{% block  title_page %}
<title>Navis - {% trans 'About Us' %}</title>
{% endblock title_page %}

{% block content_page %}


{% endblock content_page %}

navis_one/templates/navis_one/contact.html
{% extends 'navis_one/main.html' %}
{% load static i18n navis_tag %}
{% block  title_page %}
<title>Navis - {% trans 'Contact' %}</title>
{% endblock title_page %}

{% block content_page %}


{% endblock content_page %}

navis_one/templates/navis_one/include/footer.html
{% load static i18n navis_tag %}

<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="footer__about">
                    <div class="footer__logo">
                        <a href="{% url 'navis:home' %}"><img src="{% static 'img/footer-logo.png' %}"></a>
                    </div>
                    <p><b>The NAVIS trademark </b> was founded by the European company NSS Polska Sp.z.o.o in 2018,
                        Lodz, Poland.</p>
                </div>
            </div>
            <div class="col-lg-2 offset-lg-1 col-md-3 col-sm-6">
                <div class="footer__widget">
                    <h6>Shopping</h6>
                    <ul>
                        <li><a href="#">Clothing Store</a></li>
                        <li><a href="#">Trending Shoes</a></li>
                        <li><a href="#">Accessories</a></li>
                        <li><a href="#">Sale</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-3 col-sm-6">
                <div class="footer__widget">
                    <h6>Shopping</h6>
                    <ul>
                        <li><a href="#">Contact Us</a></li>
                        <li><a href="#">Payment Methods</a></li>
                        <li><a href="#">Delivary</a></li>
                        <li><a href="#">Return & Exchanges</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 offset-lg-1 col-md-6 col-sm-6">
                <div class="footer__widget">
                    <h6>Shopping</h6>
                    <ul>
                        <li><a href="#">Contact Us</a></li>
                        <li><a href="#">Payment Methods</a></li>
                        <li><a href="#">Delivary</a></li>
                        <li><a href="#">Return & Exchanges</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="footer__copyright__text">
                    <p>Copyright ©
                        <script>
                            document.write(new Date().getFullYear());
                        </script>
                        2018. All rights reserved | Navis.One
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>

<div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch">+</div>
        <form class="search-model-form">
            <input type="text" id="search-input" placeholder="Search here.....">
        </form>
    </div>
</div>

navis_one/templates/navis_one/include/header.html
{% load static i18n navis_tag %}

<header class="header">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-3">
                <div class="header__logo">
                    <a href="{% url 'navis:home' %}"><img src="{% static 'img/logo.png' %}"></a>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <nav class="header__menu mobile-menu">
                    <ul>
                        <li class="active"><a href="{% url 'navis:home' %}">{% trans 'Home' %}</a></li>
                        <li><a href="#">{% trans 'Catalog' %}</a>
                            <ul class="dropdown">
                                <li><a href="#">{% trans 'Headlight' %}</a></li>
                                <li><a href="#">{% trans 'Wiper Blades' %}</a></li>
                            </ul>
                        </li>
                        <li><a href="#">{% trans 'About' %}</a></li>
                        <li><a href="#">{% trans 'Contacts' %}</a></li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3 col-md-3">
                <div class="header__nav__option">
                    <a href="#" class="search-switch"><img src="{% static 'img/icon/search.png' %}" alt=""></a>
                </div>
            </div>
        </div>
        <div class="canvas__open"><i class="fa fa-bars"></i></div>
    </div>
</header>

navis_one/templates/navis_one/index.html
{% extends 'navis_one/main.html' %}
{% load static i18n navis_tag %}
{% block  title_page %}
<title>Navis - {% trans 'Home' %}</title>
{% endblock title_page %}

{% block content_page %}

<!-- Hero Section Begin -->
<section class="hero">
    <div class="hero__slider owl-carousel">

        <div class="hero__items set-bg" data-setbg="{% static 'img/hero/hero-1.jpg' %}">
            <div class="container">
                <div class="row">
                    <div class="col-xl-5 col-lg-7 col-md-8">
                        <div class="hero__text">
                            <h6>Summer Collection</h6>
                            <h2>Fall - Winter Collections 2030</h2>
                            <p>A specialist label creating luxury essentials. Ethically crafted with an unwavering
                                commitment to exceptional quality.</p>
                            <a href="#" class="primary-btn">Catalog <span class="arrow_right"></span></a>
                            <div class="hero__social">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-instagram"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="hero__items set-bg" data-setbg="{% static 'img/hero/hero-2.jpg' %}">
            <div class="container">
                <div class="row">
                    <div class="col-xl-5 col-lg-7 col-md-8">
                        <div class="hero__text">
                            <h6>Summer Collection</h6>
                            <h2>Fall - Winter Collections 2030</h2>
                            <p>A specialist label creating luxury essentials. Ethically crafted with an unwavering
                                commitment to exceptional quality.</p>
                            <a href="#" class="primary-btn">Catalog <span class="arrow_right"></span></a>
                            <div class="hero__social">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-instagram"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="hero__items set-bg" data-setbg="{% static 'img/hero/hero-3.jpg' %}">
            <div class="container">
                <div class="row">
                    <div class="col-xl-5 col-lg-7 col-md-8">
                        <div class="hero__text">
                            <h6>Summer Collection</h6>
                            <h2>Fall - Winter Collections 2030</h2>
                            <p>A specialist label creating luxury essentials. Ethically crafted with an unwavering
                                commitment to exceptional quality.</p>
                            <a href="#" class="primary-btn">Catalog <span class="arrow_right"></span></a>
                            <div class="hero__social">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-instagram"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="hero__items set-bg" data-setbg="{% static 'img/hero/hero-4.jpg' %}">
            <div class="container">
                <div class="row">
                    <div class="col-xl-5 col-lg-7 col-md-8">
                        <div class="hero__text">
                            <h6>Summer Collection</h6>
                            <h2>Fall - Winter Collections 2030</h2>
                            <p>A specialist label creating luxury essentials. Ethically crafted with an unwavering
                                commitment to exceptional quality.</p>
                            <a href="#" class="primary-btn">Catalog <span class="arrow_right"></span></a>
                            <div class="hero__social">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-instagram"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</section>
<!-- Hero Section End -->

<!-- Banner Section Begin -->
<section class="banner spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-7 offset-lg-4">
                <div class="banner__item">
                    <div class="banner__item__pic">
                        <img src="{% static 'img/banner/banner-1.jpg' %}" alt="">
                    </div>
                    <div class="banner__item__text">
                        <h2>Wiper Blade PRO</h2>
                        <a href="#">Catalog</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-5">
                <div class="banner__item banner__item--middle">
                    <div class="banner__item__pic">
                        <img src="{% static 'img/banner/banner-2.jpg' %}" alt="">
                    </div>
                    <div class="banner__item__text">
                        <h2>Headlight LED</h2>
                        <a href="#">Catalog</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-7">
                <div class="banner__item banner__item--last">
                    <div class="banner__item__pic">
                        <img src="{% static 'img/banner/banner-3.jpg' %}" alt="">
                    </div>
                    <div class="banner__item__text">
                        <h2>Wiper Blade Standart</h2>
                        <a href="#">Catalog</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Banner Section End -->

<!-- Instagram Section Begin -->
<section class="instagram spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="instagram__pic">
                    <div class="instagram__pic__item set-bg" data-setbg="{% static 'img/instagram/instagram-1.jpg' %}"></div>
                    <div class="instagram__pic__item set-bg" data-setbg="{% static 'img/instagram/instagram-2.jpg' %}"></div>
                    <div class="instagram__pic__item set-bg" data-setbg="{% static 'img/instagram/instagram-3.jpg' %}"></div>
                    <div class="instagram__pic__item set-bg" data-setbg="{% static 'img/instagram/instagram-4.jpg' %}"></div>
                    <div class="instagram__pic__item set-bg" data-setbg="{% static 'img/instagram/instagram-5.jpg' %}"></div>
                    <div class="instagram__pic__item set-bg" data-setbg="{% static 'img/instagram/instagram-6.jpg' %}"></div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="instagram__text">
                    <h2>Instagram</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore magna aliqua.</p>
                    <h3>#Navis_One</h3>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Instagram Section End -->

{% endblock content_page %}

navis_one/templates/navis_one/main.html
{% load static i18n navis_tag %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    {% block title_page %}
    {% endblock %}

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="robots" content="noindex, follow">
    <meta name="description" content="Navis, Navis One, Auto Parts, Navis Auto Parts">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&display=swap"
          rel="stylesheet">

    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>

    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awasome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>
<!-- Page Preloder -->
<div id="preloder">
    <div class="loader"></div>
</div>

{% include 'navis_one/include/header.html' %}

{% block content_page %}
{% endblock %}

{% include 'navis_one/include/footer.html' %}

<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/jquery.countdown.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.nicescroll.min.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/jquery.slicknav.js' %}"></script>
<script src="{% static 'js/mixitup.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>

<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

navis_one/templates/navis_one_old/include/footer.html
{% load static i18n navis_tag %}

<footer id="footer" class="bg-one">
    <div class="top-footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-3 col-md-3 col-lg-3">
                    <h3>About Us</h3>
                    <p><b>The NAVIS trademark </b> was founded by the European company NSS Polska Sp.z.o.o in 2018,
                        Lodz, Poland.
                </div>

                <div class="col-sm-3 col-md-3 col-lg-3">
                    <ul>
                        <li><h3>Our Products</h3></li>
                        {% get_categories as categories %}
                        {% for category in categories %}
                        <li><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="col-sm-3 col-md-3 col-lg-3">
                    <ul>
                        <li><h3>Quick Links</h3></li>
                        <li><a href="{% url 'navis:home' %}">Home</a></li>
                        <li><a href="{% url 'navis:about' %}">About Us</a></li>
                        <li><a href="{% url 'navis:contact' %}">Contact</a></li>
                    </ul>
                </div>

                <div class="col-sm-3 col-md-3 col-lg-3">
                    <ul>
                        <li><h3>Connect with us Socially</h3></li>
                        <li><a href="#">Facebook</a></li>
                        <li><a href="#">Twitter</a></li>
                        <li><a href="#">Youtube</a></li>
                    </ul>
                </div>

            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <h5>Copyright by NAVIS 2020. All rights reserved.</h5>
    </div>
</footer>

navis_one/templates/navis_one_old/include/header.html
{% load static i18n navis_tag %}

<header class="navigation fixed-top">
    <div class="container">

        <nav class="navbar navbar-expand-lg navbar-light">

            <!-- logo -->
            <!--      <a class="navbar-brand logo" href="index.html">-->
            <!--        <img class="logo-default" src="images/logo.png" alt="logo"/>-->
            <!--        <img class="logo-white" src="images/logo-white.png" alt="logo"/>-->
            <!--      </a>-->
            <!-- /logo -->

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
                    aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navigation">
                <ul class="navbar-nav ml-auto text-center">
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'navis:home' %}">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Products
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% get_categories as categories %}
                            {% for category in categories %}
                            <a class="dropdown-item" href="{{ category.get_absolute_url }}">{{ category.name }}</a>
                            {% endfor %}
                        </div>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'navis:about' %}">About Us</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'navis:contact' %}">Contact</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="javascript:void(0)" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {% trans 'Language' %}
                        </a>
                        <form action="{% url 'set_language' %}" method="post">
                            {% csrf_token %}
                            <input name="next" type="hidden"
                                   value="{{ request.get_full_path|slice:'3:' }}"/>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                {% get_current_language as LANGUAGE_CODE %}
                                {% get_available_languages as LANGUAGES %}
                                {% get_language_info_list for LANGUAGES as languages %}
                                {% for language in languages %}
                                <button type="submit" name="language" class="dropdown-item"
                                        value="{{ language.code }}"
                                        class="{% if language.code == LANGUAGE_CODE %}selected{% endif %}">
                                    {{ language.name_local }}
                                </button>
                                {% endfor %}
                            </div>
                        </form>
                    </li>
                </ul>
            </div>
        </nav>

    </div>
</header>

navis_one/templates/navis_one_old/product/product_detail.html
{% extends 'navis_one/product/main.html' %}
{% load static i18n navis_tag %}
{% block  title_page %}
<title>Navis - {{ category.name }} | {{ product.article }}</title>
{% endblock title_page %}


{% block product_page %}

<section class="single-page-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3>{{ product.name }} {{ product.article }}</h3>
            </div>
        </div>
    </div>
</section>

<div class="breadcumb_area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <ol class="breadcrumb d-flex align-items-center">
                    <li class="breadcrumb-item"><a href="{% url 'navis:home' %}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
                    <li class="breadcrumb-item active">{{ product.name }} {{ product.article }}</li>
                </ol>
                <a href="{{ category.get_absolute_url }}" class="backToHome d-block">
                    <i class="fa fa-angle-double-left"></i> Back to Category</a>
            </div>
        </div>
    </div>
</div>

<section class="single_product_details_area section_padding_0_100">
    <div class="container">
        <div class="row">

            <div class="col-12 col-md-6">
                <div class="single_product_thumb">
                    <div id="product_details_slider" class="carousel slide" data-ride="carousel">

                        <ol class="carousel-indicators">
                            <li class="active" data-target="#product_details_slider" data-slide-to="0"
                                style="background-image: url(img/product-img/product-9.jpg);">
                            </li>
                        </ol>

                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <a class="gallery_img" href="img/product-img/product-9.jpg">
                                    <img class="d-block w-100" src="img/product-img/product-9.jpg">
                                </a>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

            <div class="col-12 col-md-6">
                <div class="single_product_desc">

                    <h4 class="title">{{ product.name }} {{ product.article }}</h4>
                    <h4 class="price">{{ product.specification }}</h4>

                    <div id="accordion" role="tablist">

                        <div class="card">
                            <div class="card-header" role="tab" id="headingOne">
                                <h6 class="mb-0">
                                    <a data-toggle="collapse" href="#collapseOne" aria-expanded="true"
                                       aria-controls="collapseOne">Information</a>
                                </h6>
                            </div>

                            <div id="collapseOne" class="collapse show" role="tabpanel" aria-labelledby="headingOne"
                                 data-parent="#accordion">
                                <div class="card-body">
                                    <p>
                                       {{ product.advanced_description|safe }}
                                    </p>
                                </div>
                            </div>
                        </div>

                    </div>

                </div>
            </div>

        </div>
    </div>
</section>

{% endblock product_page %}

navis_one/templates/navis_one_old/product/product_sidebar.html
{% load static i18n navis_tag %}